import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import logo from '../public/logo.png'
import background from '../public/bg-right.png'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Guarda Imperial</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className={styles.container}>
        <div className={styles.left}>
            <div className={styles.logo}>
              <Image src={logo} alt="logo"/>
            </div>
            <h1 className={styles.title}>Já é um(a) <span>Guarda Imperial?</span></h1>
            <input className={styles.inputemail} type="text" name="email" id="email" placeholder="Digite seu e-mail"/>
            <button className={styles.button}>Acesse sua credencial</button>
            <h2 className={styles.registry}>Registre-se agora!</h2>

            <div className={styles.bottom}>
                <div className={styles.left}>
                    <span>Siga o Império</span>
                </div>
                <div className={styles.right}>
                    <span><a href="http://twitter.com" target="_blank">Twitter</a></span>
                    <span><a href="http://facebook.com" target="_blank">Facebook</a></span>
                    <span><a href="http://instagram.com" target="_blank">Instagram</a></span>
                </div>
            </div>
        </div>

        <div className={`${styles.right} ${styles.background}`}>
          <Image src={background} alt="imperial"/>
        </div>
      </div>
      
    </div>
  )
}
